name: Linting

on: pull_request

jobs:
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9.0.0

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/hydrogen"
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile

      - run: pnpm lint:prettier:check

  eslint:
    name: Eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: pnpm/action-setup@v4
        with:
          version: 9.0.0

      - uses: actions/setup-node@v4
        with:
          node-version: "lts/hydrogen"
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile

      - run: pnpm lint:eslint:check
